Desarrollo/SVB/fuente/svb_backend/.gitignore
Desarrollo/SVB/fuente/svb_backend/manage.py
Desarrollo/SVB/fuente/svb_backend/svb_backend/asgi.py
Desarrollo/SVB/fuente/svb_backend/svb_backend/settings/base.py
Desarrollo/SVB/fuente/svb_backend/svb_backend/settings/dev.py
Desarrollo/SVB/fuente/svb_backend/svb_backend/settings/prod.py
Desarrollo/SVB/fuente/svb_backend/svb_backend/urls.py
Desarrollo/SVB/fuente/svb_backend/svb_backend/wsgi.py

Se sube proyecto base para el backend.

Inicializa proyecto backend

---

Desarrollo/SVB/fuente/svb_frontend/listaProductos.html

Se agrega en la Frontend interfaz de lista de productos

Se agregó interfaz de Lista de productos

---

Desarrollo/SVB/fuente/svb_frontend/home.html
Desarrollo/SVB/fuente/svb_frontend/listaProductos.html
Desarrollo/SVB/fuente/svb_frontend/registro.html

Se actualizaron interfaz de registro de usuario y Lista de productos

Se actualiza  interfaz Registro y Lista de productos

---

Desarrollo/SVB/fuente/svb_frontend/detalleProducto.html
Desarrollo/SVB/fuente/svb_frontend/login.html

Se crea el login

---

Desarrollo/SVB/fuente/svb_frontend/login.html

Corrección del  formulario login

correccion de un campo del login

---

Desarrollo/SVB/fuente/svb_frontend/profile.html

Creación de la interfaz del perfil de usuario

Se agrega interfaz de perfil de usuario

---

Desarrollo/SVB/fuente/svb_frontend/login.html

Se agrega link de login a registro

Agregué enlace a registro

---

Desarrollo/SVB/fuente/svb_frontend/CatalogoProductos.html
Desarrollo/SVB/fuente/svb_frontend/Proveedores.html

Creación de mantenimiento de producto y proveedores ->Front

Se agrega interfaz gráfica de mantenimiento de productos y proveedores

---

Desarrollo/SVB/fuente/svb_frontend/Categoria.html

Interfaz de mantenimiento de Categoría ->Frontend

Se crea interfaz gráfica de mantenimiento de Categoría

---

Desarrollo/SVB/fuente/svb_backend/apps/orders/serializers.py
Desarrollo/SVB/fuente/svb_backend/apps/products/models.py
Desarrollo/SVB/fuente/svb_backend/requirements.txt

Agrega todos los campos de producto en order item serializer

Modifica serializer de order item.

---

Desarrollo/SVB/fuente/svb_backend/svb_backend/settings/base.py
Desarrollo/SVB/fuente/svb_backend/svb_backend/urls.py

Se agrega la url de las imágenes para que se guarden ahí.

Agrega url media para las imágenes.

---

Desarrollo/SVB/fuente/svb_backend/apps/products/serializers.py
Desarrollo/SVB/fuente/svb_backend/apps/products/views.py
Desarrollo/SVB/fuente/svb_backend/requirements.txt

Se crea serializer para el response de productos cuando se recibe un método GET y se añade la librería django-filter.

Modifica response para lista de productos. Se añade django-filter.

---

Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Producto.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Home.js

Corrección para poder agregar imágenes a los productos

Tania escobedo

---

Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Categoria.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/NavBar.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/NavegacionLateral.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Producto.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/CardCategoria.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/CardProducto.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Home.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/NavBarBodega.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/NavCategoriaLateral.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/Carrito.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/NavbarPerfil.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/ProductoCart.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/ProductoXCateg.js
db.json

carrito funcional

---

Desarrollo/SVB/fuente/svb_frontend/Integración/src/App.css
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Routes.js

modifiqué rutas y estilos css

---

Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Home.js

correción sobre Id de categorias en el home.js

correción sobre Id de categorias en el home.js

---

Desarrollo/SVB/fuente/svb_backend/apps/orders/urls.py
Desarrollo/SVB/fuente/svb_backend/apps/orders/views.py

Ruta de emergencia para crear órdenes, incluye el pago

Crea ruta alternativa para crear órdenes.

---

Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Login.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Producto.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Registro.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/Carrito.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/NavbarPerfil.js

flujo básico

---

Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Producto.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/Carrito.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/Usuario.js

arreglando la orden

---

Desarrollo/SVB/fuente/svb_backend/apps/orders/views.py
Desarrollo/SVB/fuente/svb_frontend/Integración/.env
Desarrollo/SVB/fuente/svb_frontend/Integración/.gitignore
Desarrollo/SVB/fuente/svb_frontend/Integración/package-lock.json
Desarrollo/SVB/fuente/svb_frontend/Integración/package.json
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Categoria.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Login.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/NavBar.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/NavegacionLateral.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Producto.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Proveedor.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Registro.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Home.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/NavBarBodega.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/NavCategoriaLateral.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/Carrito.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/NavbarPerfil.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/Usuario.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/ProductoXCateg.js

Agrega token y user al localstorage e implementa env.

Modificaciones varias en front

---

Desarrollo/SVB/fuente/svb_frontend/Integración/.env
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/Carrito.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/NavbarPerfil.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/Usuario.js

impl logout

---

Desarrollo/SVB/fuente/svb_frontend/Integración/public/index.html
Desarrollo/SVB/fuente/svb_frontend/Integración/src/App.css
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Categoria.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/NavBar.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/NavegacionLateral.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/CardProducto.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/NavCategoriaLateral.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/NotFound.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/Carrito.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/Usuario.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/ProductoXCateg.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Routes.js

se agrega page NotFound y se corrige el NavLateral->producXcateg

Se agrega page Not found y se fixeo NavLateral de productos x categoria

---

Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/Carrito.js

fixed total

---

Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/Carrito.js

se mejora el alert después de la compra

se mejora el alert después de la compra

---

Desarrollo/SVB/fuente/svb_frontend/Integración/.env
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/NavegacionLateral.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Producto.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Reporte.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/Carrito.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Routes.js

se agrega maquetado de reportes

se agrega maquetado de reportes

---

Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Reporte.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/Perfil/Usuario.js

Se implementa reporte de venta por fecha y producto

Se implementa reporte de venta por fecha y producto

---

Desarrollo/SVB/fuente/svb_frontend/Integración/package-lock.json
Desarrollo/SVB/fuente/svb_frontend/Integración/package.json
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Admin/Registro.js

validación del registro con formik y Yup

 se agrega validación del registro 

---

Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/CardProducto.js
Desarrollo/SVB/fuente/svb_frontend/Integración/src/Components/Cliente/NavBarBodega.js

Se crea manual de usuario
